# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SeqListWidget = QtWidgets.QListWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SeqListWidget.sizePolicy().hasHeightForWidth())
        self.SeqListWidget.setSizePolicy(sizePolicy)
        self.SeqListWidget.setMinimumSize(QtCore.QSize(150, 300))
        self.SeqListWidget.setObjectName("SeqListWidget")
        self.verticalLayout_3.addWidget(self.SeqListWidget)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_4 = FingerButton(self.groupBox)
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 3, 0, 1, 1)
        self.pushButton_5 = FingerButton(self.groupBox)
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 4, 0, 1, 1)
        self.pushButton_3 = FingerButton(self.groupBox)
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.pushButton_2 = FingerButton(self.groupBox)
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_1 = FingerButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        self.pushButton_1.setCheckable(True)
        self.pushButton_1.setChecked(True)
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout_2.addWidget(self.pushButton_1, 0, 0, 1, 1)
        self.pushButton_6 = FingerButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 0, 1, 1, 1)
        self.pushButton_7 = FingerButton(self.groupBox)
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.pushButton_8 = FingerButton(self.groupBox)
        self.pushButton_8.setCheckable(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 2, 1, 1, 1)
        self.pushButton_9 = FingerButton(self.groupBox)
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_2.addWidget(self.pushButton_9, 3, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = MainDisplayBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.img_11 = TrackingLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_11.sizePolicy().hasHeightForWidth())
        self.img_11.setSizePolicy(sizePolicy)
        self.img_11.setMinimumSize(QtCore.QSize(320, 240))
        self.img_11.setMouseTracking(True)
        self.img_11.setFrameShape(QtWidgets.QFrame.Box)
        self.img_11.setScaledContents(False)
        self.img_11.setAlignment(QtCore.Qt.AlignCenter)
        self.img_11.setObjectName("img_11")
        self.gridLayout_3.addWidget(self.img_11, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.open = QtWidgets.QAction(MainWindow)
        self.open.setObjectName("open")
        self.save = QtWidgets.QAction(MainWindow)
        self.save.setObjectName("save")
        self.quit = QtWidgets.QAction(MainWindow)
        self.quit.setObjectName("quit")
        self.action_export = QtWidgets.QAction(MainWindow)
        self.action_export.setObjectName("action_export")
        self.menu.addAction(self.open)
        self.menu.addAction(self.save)
        self.menu.addAction(self.action_export)
        self.menu.addSeparator()
        self.menu.addAction(self.quit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.quit.triggered.connect(MainWindow.close)
        self.open.triggered.connect(MainWindow.menuOpenTriggered)
        self.save.triggered.connect(MainWindow.menuSaveTriggered)
        self.SeqListWidget.currentRowChanged['int'].connect(MainWindow.listWidgetOnCurrentRowChanged)
        self.groupBox_3.resized_signal.connect(MainWindow.mainDisplayBoxResized)
        self.img_11.label_click_signal['int','int','int'].connect(MainWindow.trackingLabelOnClicked)
        self.pushButton_1.finger_button_signal['int'].connect(MainWindow.fingerButtonClicked)
        self.pushButton_6.finger_button_signal['int'].connect(MainWindow.fingerButtonClicked)
        self.pushButton_2.finger_button_signal['int'].connect(MainWindow.fingerButtonClicked)
        self.pushButton_7.finger_button_signal['int'].connect(MainWindow.fingerButtonClicked)
        self.pushButton_3.finger_button_signal['int'].connect(MainWindow.fingerButtonClicked)
        self.pushButton_8.finger_button_signal['int'].connect(MainWindow.fingerButtonClicked)
        self.pushButton_4.finger_button_signal['int'].connect(MainWindow.fingerButtonClicked)
        self.pushButton_9.finger_button_signal['int'].connect(MainWindow.fingerButtonClicked)
        self.pushButton_5.finger_button_signal['int'].connect(MainWindow.fingerButtonClicked)
        self.action_export.triggered.connect(MainWindow.menuExportTriggered)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "标签图标注程序"))
        self.groupBox_2.setTitle(_translate("MainWindow", "序列"))
        self.groupBox.setTitle(_translate("MainWindow", "标注特征点"))
        self.pushButton_4.setText(_translate("MainWindow", "point 4"))
        self.pushButton_5.setText(_translate("MainWindow", "point 5"))
        self.pushButton_3.setText(_translate("MainWindow", "point 3"))
        self.pushButton_2.setText(_translate("MainWindow", "point 2"))
        self.pushButton_1.setText(_translate("MainWindow", "point 1"))
        self.pushButton_6.setText(_translate("MainWindow", "point 6"))
        self.pushButton_7.setText(_translate("MainWindow", "point 7"))
        self.pushButton_8.setText(_translate("MainWindow", "point 8"))
        self.pushButton_9.setText(_translate("MainWindow", "point 9"))
        self.groupBox_3.setTitle(_translate("MainWindow", "标注图像"))
        self.img_11.setText(_translate("MainWindow", "机位1 标签图"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">标签图</span></p><p align=\"center\">鼠标左键打标</p><p align=\"center\">右键设置空标签</p></body></html>"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.open.setText(_translate("MainWindow", "打开工作目录"))
        self.save.setText(_translate("MainWindow", "保存标签"))
        self.quit.setText(_translate("MainWindow", "退出"))
        self.action_export.setText(_translate("MainWindow", "导出标签"))


from fingerbutton import FingerButton
from maindisplaybox import MainDisplayBox
from trackinglabel import TrackingLabel
